---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Sample Cluster'

Parameters:
  NetworkStack:
    Type: String
    Description: Name of the NetworkStack
    Default: EKS-NET

  ClusterName:
    Type: String
    Default: MyCluster
    Description: The name of your cluster

  KubernetesVersion:
    Type: String
    Default: 1.11
    Description: The version of Kubernetes to start your cluster with

Resources:
  AWSEKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Sub ${AWS::StackName}-${ClusterName}
      ResourcesVpcConfig:
        SecurityGroupIds: [ {"Fn::ImportValue": !Sub "${NetworkStack}-SecurityGroup"} ]
        SubnetIds: !Split [",",{"Fn::ImportValue": !Sub "${NetworkStack}-SubnetIDs"}]
      RoleArn: {"Fn::ImportValue": !Sub "${NetworkStack}-RoleArn"}
      Version: !Ref KubernetesVersion

Outputs:
    ClusterName:
      Description: The Cluster name
      Value: !Sub ${AWS::StackName}-${ClusterName}
      Export:
        Name: !Sub "${AWS::StackName}-ClusterName"